### ISSUE TITLE
Deploy on conda-forge

### ISSUE THREAD

**Issue by woutdenolf** [miguelgrinberg/simple-websocket#21]
Could we make a conda-forge feedstock for this project?

```
grayskull pypi simple-websocket
```

The generate recipe

```yaml
{% set name = "simple-websocket" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/simple-websocket-{{ version }}.tar.gz
  sha256: b25387c08a6455f8fac087117ad40dd56b9d1df28e18bd1b0b0a374c49a4f993

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - wsproto

test:
  imports:
    - simple_websocket
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/miguelgrinberg/simple-websocket
  summary: Simple WebSocket server and client for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - miguelgrinberg
```
